import type { MusicProvider } from "../provider";
import { authorizeUrl, exchangeCode, refresh } from "./auth";
import {
  getArtist,
  getArtistFollowed,
  getArtistTracks,
  getFeedPage,
  getLikesPage,
  getMe,
  getPlaylists,
  getPlaylistTracks,
  getRelatedTracks,
  getTrackSocial,
  getWaveform,
  resolveStream,
  searchArtists,
  searchTracks,
  setArtistFollowed,
  setTrackLiked,
} from "./api";

export const soundcloudProvider: MusicProvider = {
  authorizeUrl,
  exchangeCode,
  refresh,
  getMe,
  getLikesPage,
  getPlaylists,
  getPlaylistTracks,
  getRelatedTracks,
  getFeedPage,
  searchTracks,
  searchArtists,
  getArtist,
  getArtistTracks,
  getArtistFollowed,
  resolveStream,
  getWaveform,
  getTrackSocial,
  setTrackLiked,
  setArtistFollowed,
};
